/**
 * CppExporter.js
 * Generates an Arduino / ESP-IDF C++ header file (.h) with PROGMEM frame tables
 * and a hardware-agnostic matrix playback helper.
 */

export class CppExporter {
  constructor(matrixState) {
    this.state = matrixState;
  }

  generateHeaderCode() {
    const safeName = (this.state.name || 'anim_sequence').replace(/[^a-zA-Z0-9_]/g, '_').toUpperCase();
    const w = this.state.width;
    const h = this.state.height;
    const totalPixels = w * h;
    const frameCount = this.state.frames.length;

    let durationsStr = 'const uint16_t ' + safeName + '_DURATIONS[' + frameCount + '] PROGMEM = {\n  ';
    for (let i = 0; i < frameCount; i++) {
      durationsStr += this.state.frames[i].durationMs + (i < frameCount - 1 ? ', ' : '');
      if ((i + 1) % 12 === 0 && i < frameCount - 1) durationsStr += '\n  ';
    }
    durationsStr += '\n};\n';

    let framesStr = 'const uint8_t ' + safeName + '_FRAMES[' + frameCount + '][' + totalPixels + '] PROGMEM = {\n';

    for (let f = 0; f < frameCount; f++) {
      framesStr += '  // Frame ' + f + '\n  { ';
      const frame = this.state.frames[f];
      for (let p = 0; p < totalPixels; p++) {
        const val = frame.data[p];
        framesStr += (val > 0 ? '0x' + (val < 16 ? '0' : '') + val.toString(16) : '0') + (p < totalPixels - 1 ? ', ' : '');
        if ((p + 1) % 20 === 0 && p < totalPixels - 1) framesStr += '\n    ';
      }
      framesStr += ' }' + (f < frameCount - 1 ? ',\n' : '\n');
    }
    framesStr += '};\n';

    const header = `/**
 * ${safeName}.h
 * Auto-generated by Animatrix Studio (Hardware-Agnostic 8-bit PWM Animation)
 * Matrix: ${w}x${h} (${totalPixels} LEDs) | Total Frames: ${frameCount} | FPS: ${this.state.globalFps}
 */

#ifndef ${safeName}_H
#define ${safeName}_H

#include <Arduino.h>

#define ${safeName}_WIDTH        ${w}
#define ${safeName}_HEIGHT       ${h}
#define ${safeName}_TOTAL_LEDS   ${totalPixels}
#define ${safeName}_FRAME_COUNT  ${frameCount}
#define ${safeName}_FPS          ${this.state.globalFps}

${durationsStr}
${framesStr}

/**
 * Example helper function to render a frame.
 * Connect 'setPixel(x, y, brightness)' to your matrix driver (e.g. IS31FL3731, WS2812, etc.)
 */
/*
template <typename PixelSetter>
void play_${safeName.toLowerCase()}_frame(uint16_t frameIdx, PixelSetter setPixel) {
  if (frameIdx >= ${safeName}_FRAME_COUNT) return;
  for (uint8_t y = 0; y < ${safeName}_HEIGHT; y++) {
    for (uint8_t x = 0; x < ${safeName}_WIDTH; x++) {
      uint8_t brightness = pgm_read_byte(&(${safeName}_FRAMES[frameIdx][y * ${safeName}_WIDTH + x]));
      setPixel(x, y, brightness);
    }
  }
}
*/

#endif // ${safeName}_H
`;

    return header;
  }

  downloadHeader() {
    const code = this.generateHeaderCode();
    const safeName = (this.state.name || 'daft_punk_anim').replace(/[^a-zA-Z0-9_]/g, '_');
    const filename = `${safeName}.h`;
    const blob = new Blob([code], { type: 'text/x-c++hdr' });
    const url = URL.createObjectURL(blob);

    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
}
